# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .custodian_client import CustodianClient
from .version import VERSION

__all__ = ['CustodianClient']

__version__ = VERSION

